export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'
export const CREATE_COMMENT_RESET = 'CREATE_COMMENT_RESET'

export const LIKE_COMMENT_REQUEST = 'LIKE_COMMENT_REQUEST'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL'
export const LIKE_COMMENT_RESET = 'LIKE_COMMENT_RESET'

export const UNLIKE_COMMENT_REQUEST = 'UNLIKE_COMMENT_REQUEST'
export const UNLIKE_COMMENT_SUCCESS = 'UNLIKE_COMMENT_SUCCESS'
export const UNLIKE_COMMENT_FAIL = 'UNLIKE_COMMENT_FAIL'
export const UNLIKE_COMMENT_RESET = 'UNLIKE_COMMENT_RESET'