export const MESSAGE_ADD_USER='MESSAGE_ADD_USER'

export const MESSAGE_ADD_REQUEST = 'MESSAGE_ADD_REQUEST'
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS'
export const MESSAGE_ADD_FAIL = 'MESSAGE_ADD_FAIL'

export const CONVERSATION_GET_REQUEST = 'CONVERSATION_GET_REQUEST'
export const CONVERSATION_GET_SUCCESS = 'CONVERSATION_GET_SUCCESS'
export const CONVERSATION_GET_FAIL = 'CONVERSATION_GET_FAIL'

export const MESSAGE_GET_REQUEST = 'MESSAGE_GET_REQUEST'
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS'
export const MESSAGE_GET_FAIL = 'MESSAGE_GET_FAIL'

export const MESSAGE_GET_MORE_REQUEST = 'MESSAGE_GET_MORE_REQUEST'
export const MESSAGE_GET_MORE_SUCCESS = 'MESSAGE_GET_MORE_SUCCESS'
export const MESSAGE_GET_MORE_FAIL = 'MESSAGE_GET_MORE_FAIL'

export const MESSAGE_DELETE_REQUEST = 'MESSAGE_DELETE_REQUEST'
export const MESSAGE_DELETE_SUCCESS = 'MESSAGE_DELETE_SUCCESS'
export const MESSAGE_DELETE_FAIL = 'MESSAGE_DELETE_FAIL'

export const CONVERSATION_DELETE_REQUEST = 'CONVERSATION_DELETE_REQUEST'
export const CONVERSATION_DELETE_SUCCESS = 'CONVERSATION_DELETE_SUCCESS'
export const CONVERSATION_DELETE_FAIL = 'CONVERSATION_DELETE_FAIL'

export const CHECK_ONLINE = 'CHECK_ONLINE'
