export const CREATE_NOTIFY_REQUEST = 'CREATE_NOTIFY_REQUEST'
export const CREATE_NOTIFY_SUCCESS = 'CREATE_NOTIFY_SUCCESS'
export const CREATE_NOTIFY_FAIL = 'CREATE_NOTIFY_FAIL'

export const REMOVE_NOTIFY_REQUEST = 'REMOVE_NOTIFY_REQUEST'
export const REMOVE_NOTIFY_SUCCESS = 'REMOVE_NOTIFY_SUCCESS'
export const REMOVE_NOTIFY_FAIL = 'REMOVE_NOTIFY_FAIL'

export const GET_NOTIFY_REQUEST = 'GET_NOTIFY_REQUEST'
export const GET_NOTIFY_SUCCESS = 'GET_NOTIFY_SUCCESS'
export const GET_NOTIFY_FAIL = 'GET_NOTIFY_FAIL'

export const READ_NOTIFY_REQUEST = 'READ_NOTIFY_REQUEST'
export const READ_NOTIFY_SUCCESS = 'READ_NOTIFY_SUCCESS'
export const READ_NOTIFY_FAIL = 'READ_NOTIFY_FAIL'

export const DELETE_ALL_NOTIFY_REQUEST = 'DELETE_ALL_NOTIFY_REQUEST'
export const DELETE_ALL_NOTIFY_SUCCESS = 'DELETE_ALL_NOTIFY_SUCCESS'
export const DELETE_ALL_NOTIFY_FAIL = 'DELETE_ALL_NOTIFY_FAIL'

