export const PROFILE_GETUSER_REQUEST = 'PROFILE_GETUSER_REQUEST'
export const PROFILE_GETUSER_SUCCESS = 'PROFILE_GETUSER_SUCCESS'
export const PROFILE_GETUSER_FAIL = 'PROFILE_GETUSER_FAIL'
export const PROFILE_GETUSER_RESET = 'PROFILE_GETUSER_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'