export const PROFILE_GET_REQUEST = 'PROFILE_GETUSER_REQUEST'
export const PROFILE_GETUSER_SUCCESS = 'PROFILE_GETUSER_SUCCESS'
export const PROFILE_GETPOST_SUCCESS='PROFILE_GETPOST_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GETUSER_FAIL'

export const PROFILE_GETUSER_RESET = 'PROFILE_GETUSER_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_FOLLOW_PROFILE = 'USER_FOLLOW_PROFILE'
export const USER_UNFOLLOW_PROFILE = 'USER_UNFOLLOW_PROFILE'



