export const PROFILE_GETUSER_REQUEST = 'PROFILE_GETUSER_REQUEST'
export const PROFILE_GETUSER_SUCCESS = 'PROFILE_GETUSER_SUCCESS'
export const PROFILE_GETUSER_FAIL = 'PROFILE_GETUSER_FAIL'
export const PROFILE_GETUSER_RESET = 'PROFILE_GETUSER_RESET'

